# Generated by Django 6.0.5 on 2026-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burgare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('beskrivning', models.TextField()),
                ('pris', models.DecimalField(decimal_places=0, max_digits=6)),
                ('bild_url', models.URLField(max_length=500)),
                ('popular', models.BooleanField(default=False)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
