# Generated by Django 6.0.5 on 2026-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgare',
            name='kategori',
            field=models.CharField(choices=[('burgers', 'Burgers'), ('sides', 'Sides'), ('dips', 'Dips')], default='burgers', max_length=20),
        ),
    ]
