# Generated by Django 6.0.5 on 2026-06-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0002_burgare_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erbjudande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('kod', models.CharField(blank=True, max_length=50)),
                ('bild_url', models.URLField(blank=True, max_length=500)),
                ('publicerad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nyhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('bild_url', models.URLField(blank=True, max_length=500)),
                ('publicerad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
