# Generated by Django 6.0.5 on 2026-06-02 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0004_rost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnvantErbjudande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anvant_datetime', models.DateTimeField(auto_now_add=True)),
                ('erbjudande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meny.erbjudande')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'erbjudande')},
            },
        ),
    ]
