# Generated by Django 6.0.5 on 2026-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0005_anvanterbjudande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('aktiv', models.BooleanField(default=True)),
                ('farg', models.CharField(default='#F5A623', max_length=7)),
                ('text_farg', models.CharField(default='#0B0B0B', max_length=7)),
                ('skapad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
