# Generated by Django 6.0.5 on 2026-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='typ',
            field=models.CharField(choices=[('static', 'Static'), ('marquee', 'Marquee')], default='static', max_length=10),
        ),
    ]
