# Generated by Django 6.0.5 on 2026-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0007_banner_typ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burgare',
            options={'ordering': ['ordning', '-skapad']},
        ),
        migrations.AddField(
            model_name='burgare',
            name='ordning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
