# Generated by Django 6.0.5 on 2026-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0008_alter_burgare_options_burgare_ordning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollAlternativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('ordning', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Poll-alternativ',
                'verbose_name_plural': 'Poll-alternativ',
                'ordering': ['ordning'],
            },
        ),
    ]
