# Generated by Django 6.0.5 on 2026-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meny', '0009_pollalternativ'),
    ]

    operations = [
        migrations.AddField(
            model_name='erbjudande',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='erbjudande',
            name='card_style',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('image', 'Image')], default='dark', max_length=10),
        ),
    ]
